### ISSUE TITLE
Problem with Husky

### ISSUE THREAD

**Issue by asifrahman18** [asifrahman18/jibonJuddho#7]
Expected:
Husky should check code format, type checking, ESLint before git push

Problem:
Whenever we try to push, husky gives an error saying it is expecting a .git folder in the same directory

Reason identified so far:
Husky requires .git file to be in the same folder, but the .git folder is present in the root folder.

**Comment by moonstruck** [comment]
Let's follow this approach.
https://stackoverflow.com/questions/64001471/pylint-with-pre-commit-and-esllint-with-husky

**Comment by asifrahman18** [comment]
https://typicode.github.io/husky/guide.html
https://typicode.github.io/husky/guide.html#custom-directory
https://stackoverflow.com/questions/64001471/pylint-with-pre-commit-and-esllint-with-husky
